### ISSUE TITLE
Fix edit profile.

### ISSUE THREAD

**Issue by visheshruparelia** [zense/nightowl#1]
Crashes when changing username.

**Comment by arkokoley** [comment]
Any work done on this?

**Comment by visheshruparelia** [comment]
Actually we need your help in understanding the code when you return. @arkokoley

**Comment by arkokoley** [comment]
@visheshruparelia, @vibhavagarwal5 can you guys meet me tomorrow night?

**Comment by visheshruparelia** [comment]
Solved.
